config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :game_studios
  resources :games do
    resources :reviews
  end
  root to: "games#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    include HTTParty
    belongs_to :game_studio
    has_many :reviews, through: :users
    has_many :users, through: :reviews
end

app/models/game_studio.rb
class GameStudio < ApplicationRecord
    has_many :games
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_studios_controller.rb
class GameStudiosController < ApplicationController
  before_action :set_game_studio, only: [:show, :edit, :update, :destroy]

  # GET /game_studios
  # GET /game_studios.json
  def index
    @game_studios = GameStudio.all
  end

  # GET /game_studios/1
  # GET /game_studios/1.json
  def show
  end

  # GET /game_studios/new
  def new
    @game_studio = GameStudio.new
  end

  # GET /game_studios/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /game_studios
  # POST /game_studios.json
  def create
    @game_studio = GameStudio.new(game_studio_params)

    respond_to do |format|
      if @game_studio.save
        format.html { redirect_to @game_studio, notice: 'Game studio was successfully created.' }
        format.json { render :show, status: :created, location: @game_studio }
      else
        format.html { render :new }
        format.json { render json: @game_studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_studios/1
  # PATCH/PUT /game_studios/1.json
  def update
    respond_to do |format|
      if @game_studio.update(game_studio_params)
        format.html { redirect_to @game_studio, notice: 'Game studio was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_studio }
      else
        format.html { render :edit }
        format.json { render json: @game_studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_studios/1
  # DELETE /game_studios/1.json
  def destroy
    @game_studio.destroy
    respond_to do |format|
      format.html { redirect_to game_studios_url, notice: 'Game studio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_studio
      @game_studio = GameStudio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_studio_params
      params.require(:game_studio).permit(:name, :location)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
 
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end


  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = current_user.games.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :released, :game_studio_id, :game_id) 
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.where(game_id: params[:game_id]).all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])
  end

  # GET /reviews/new
  def new
   @game = Game.find(params[:game_id])
   @review = current_user.reviews.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.new(review_params)
    @game = Game.find(params[:game_id])
    @review.game_id = @game.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to game_reviews_path(review_id: @review), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end
  # <%= link_to "New Review", new_game_review_path(game_id: @game.id) %>


  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    # @review = current_user.reviews.update(review_params)
    # @game = Game.find(params[:game_id])
    # @review.game_id = @game.id

    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to game_reviews_path(review_id: @review), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to games_path, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    redirect_to games_path, notice:" Not Authorized to Edit This Review" if @review.nil?
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @game = Game.find params[:id]
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:reviewed_game, :rating, :game_id, :user_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_studios_helper.rb
module GameStudiosHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game_studios/_form.html.erb
<%= form_with(model: game_studio, local: true) do |form| %>
  <% if game_studio.errors.any? 
    <div id="error_explanation">
      <h2><%= pluralize(game_studio.errors.count, "error") %> prohibited this game_studio from being saved:</h2>

      <ul>
        <% game_studio.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/game_studios/edit.html.erb
<h1>Editing Game Studio</h1>

<%= render 'form', game_studio: @game_studio %>

<%= link_to 'Show', @game_studio %> |
<%= link_to 'Back', game_studios_path %>

app/views/game_studios/index.html.erb
<h1>Game Studios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_studios.each do |game_studio| %>
      <tr>
        <td><%= game_studio.name %></td>
        <td><%= game_studio.location %></td>
        <td><%= link_to 'Show', game_studio %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/game_studios/new.html.erb
<h1>New Game Studio</h1>

<%= render 'form', game_studio: @game_studio %>

<%= link_to 'Back', game_studios_path %>

app/views/game_studios/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @game_studio.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @game_studio.location %>
</p>

<p>
  <strong>Game Studio Id:</strong>
  <%= @game_studio.id %>
</p>

<%= link_to 'Edit', edit_game_studio_path(@game_studio) %> |
<%= link_to 'Back', game_studios_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

    <div class="field">
    <%= form.label :game_studio_id %>
    <%= form.number_field :game_studio_id %>
  </div>

  

  <div class="field">
    <%= form.label :released %>
    <%= form.number_field :released %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Released</th>
      <th>Studio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.released %></td>
        <td><%= game.game_studio.name %></td>
        <%# <td> <%= image_tag("/images/wc3.jpg", :size=> "300x200") %> </td> 
        <td><%= link_to 'Show', game %></td>
      </tr>
      <%# <img src='/images/wc3.jpg'> %>
      <div class="container">
 <div class="gameimages">
   <% @images.each do |image| %>
     <%= image_tag image  %>
   <% end %>
 </div>
</div>

    <% end %>
  </tbody>
</table>

<br>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="jumbotron">
<h1 class="display-6">
<p>
  <%= @game.name %>
</p>

<p>
  <%= @game.released %>
</p>

<p>
  <%= @game.game_studio.name %>
</p>
<p>
  <%= @game.game_studio.location %>
</p>
<h1>
</div>
<%= link_to 'Back', games_path %> |
<%= link_to 'Reviews', game_reviews_path(game_id: @game.id), @reviews %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Diverge', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete,class:"nav-link" %>
      </li>
           <li class="nav-item">
       <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
      </li>
      <% else %>
        <li class="nav-item">
       <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
      </li>
           <li class="nav-item">
       <%= link_to 'Sign In',  new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
    </ul>
    </form>
  </div>
</nav>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Diverge</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
   
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: [@game, @review], local:true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field form-group">
    <%= form.label :title %>
    <%= form.label @game.name %>
  </div>

  <div class="field form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, :within => 0..5 %>
  </div>

  <div class="field form-group">
    <%= form.label :drop_Your_Review %>
    <%= form.text_area :reviewed_game, :size => "50x10"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', game_review_path %> 

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<table class="table table-striped table-bordered table-hover">
   <thead class="thead-dark">
  <thead>
    <tr>
      <th>Game</th>
      <th>Review</th>
      <th>Raiting<th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.game.name %></td>
        <td><%= review.reviewed_game %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'Edit', edit_game_review_path(:game_id, review)%><td>
        <td><%= link_to 'Destroy', game_review_path(:game_id, review), method: :delete, data: { confirm: 'Are you sure?' }
        %> </td>
      </tr> 
    <% end %>
 
  </tbody>
</table>

<br>
<%= link_to 'Back', games_path %> |
<%= link_to "New Review", new_game_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>
<%# 
<%= link_to 'Back', reviews_path %> 

app/views/reviews/show.html.erb
<p>
  <strong>Game Id:</strong>
  <%= @review.game.id %>
</p>
<p>
  <strong>Reviewed game:</strong>
  <%= @review.reviewed_game %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Back', game_reviews_path %>